name: Publish release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:

  github:
    name: github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Publish release
        uses: ghalactic/github-release-from-tag@v5
        if: github.ref_type == 'tag'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: "true"

  pypi:
    name: pypi
    runs-on: ubuntu-latest
    needs: github
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Install hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      - name: Build using hatch
        run: |
          hatch build
      - name: Publish release
        env:
          HATCH_INDEX_REPO: https://upload.pypi.org/legacy/
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}
        run: |
          hatch publish
